#!/usr/bin/env bash
# Soulacy installer — works two ways:
#
#   One-liner (piped from curl):
#     curl -fsSL https://raw.githubusercontent.com/vmodekurti/soulacy/main/install.sh | bash
#
#   Local checkout:
#     ./install.sh
#
# Defaults are non-interactive and never require sudo:
#   - Binaries land in ~/.local/bin (created if missing).
#   - Runtime config + API key are generated by `soulacy serve` itself
#     on first run (internal/config.EnsureBootstrap) — this script does
#     NOT touch ~/.soulacy/ so we don't fight the binary's own bootstrap.
#
# Environment overrides:
#   SOULACY_PREFIX=/usr/local       install binaries to /usr/local/bin (uses sudo)
#   SOULACY_REF=main                git ref to install (branch / tag / sha)
#   SOULACY_NO_AUTOSTART=1          skip the macOS LaunchAgent step
#   SOULACY_SRC=/path/to/checkout   use an existing checkout instead of cloning

set -euo pipefail

# ── Constants ────────────────────────────────────────────────────────────────
REPO_URL="https://github.com/vmodekurti/soulacy.git"
REF="${SOULACY_REF:-main}"
PREFIX="${SOULACY_PREFIX:-$HOME/.local}"
BIN_DIR="$PREFIX/bin"
NEEDS_SUDO=0
[[ "$BIN_DIR" == /usr/* || "$BIN_DIR" == /opt/* ]] && NEEDS_SUDO=1

# ── Tiny output helpers ──────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'; BOLD='\033[1m'
ok()   { printf "${GREEN}✓${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}⚠${NC}  %s\n" "$*"; }
err()  { printf "${RED}✗${NC} %s\n" "$*" >&2; exit 1; }
hdr()  { printf "\n${BOLD}%s${NC}\n" "$*"; }

printf "\n${BOLD}  Soulacy installer${NC}\n  ────────────────────────────────────────\n\n"

# ── 1. Locate or fetch the source tree ──────────────────────────────────────
hdr "Step 1: Source tree"

# Detect: are we running from inside a soulacy checkout?
SCRIPT_DIR=""
if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

if [ -n "${SOULACY_SRC:-}" ]; then
    SRC_DIR="$SOULACY_SRC"
    ok "Using explicit SOULACY_SRC: $SRC_DIR"
elif [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/go.mod" ] && grep -q soulacy "$SCRIPT_DIR/go.mod"; then
    SRC_DIR="$SCRIPT_DIR"
    ok "Using local checkout: $SRC_DIR"
else
    command -v git >/dev/null 2>&1 || err "git is required to fetch sources. Install git or set SOULACY_SRC=/path/to/checkout."
    SRC_DIR="$(mktemp -d -t soulacy-install.XXXXXX)"
    trap 'rm -rf "$SRC_DIR"' EXIT
    echo "  Cloning $REPO_URL @ $REF → $SRC_DIR"
    git clone --depth 1 --branch "$REF" "$REPO_URL" "$SRC_DIR" 2>&1 | sed 's/^/    /'
    ok "Sources fetched"
fi

# ── 2. Build ────────────────────────────────────────────────────────────────
hdr "Step 2: Build"
command -v go >/dev/null 2>&1 || err "Go 1.22+ is required to build from source. Install from https://go.dev/dl/"
GO_VERSION="$(go version | awk '{print $3}' | sed 's/go//')"
echo "  Go: $GO_VERSION"
( cd "$SRC_DIR" && make build ) || err "build failed — see output above"
[ -x "$SRC_DIR/bin/soulacy" ] || err "expected $SRC_DIR/bin/soulacy after build"
[ -x "$SRC_DIR/bin/sy" ]      || err "expected $SRC_DIR/bin/sy after build"
ok "Built bin/soulacy + bin/sy"

# ── 3. Install binaries ─────────────────────────────────────────────────────
hdr "Step 3: Install to $BIN_DIR"
if [ ! -d "$BIN_DIR" ]; then
    if [ "$NEEDS_SUDO" -eq 1 ]; then
        sudo mkdir -p "$BIN_DIR"
    else
        mkdir -p "$BIN_DIR"
    fi
fi

install_one() {
    local src="$1" dst="$2"
    if [ "$NEEDS_SUDO" -eq 1 ]; then
        sudo install -m 0755 "$src" "$dst"
    else
        install -m 0755 "$src" "$dst" 2>/dev/null || { cp "$src" "$dst" && chmod 0755 "$dst"; }
    fi
}

install_one "$SRC_DIR/bin/soulacy" "$BIN_DIR/soulacy"
install_one "$SRC_DIR/bin/sy"      "$BIN_DIR/sy"
ok "Installed: $BIN_DIR/soulacy"
ok "Installed: $BIN_DIR/sy"

# ── 4. PATH check ───────────────────────────────────────────────────────────
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
    warn "$BIN_DIR is NOT on your PATH yet."
    warn "  Add this to your shell rc (~/.zshrc, ~/.bashrc):"
    warn "      export PATH=\"$BIN_DIR:\$PATH\""
    warn "  Then open a new terminal, or run:  export PATH=\"$BIN_DIR:\$PATH\""
fi

# ── 5. Optional: macOS auto-start (only when not piped + on macOS) ──────────
INTERACTIVE=0
[ -t 0 ] && INTERACTIVE=1
if [ "${SOULACY_NO_AUTOSTART:-0}" != "1" ] && [ "$(uname -s)" = "Darwin" ] && [ -f "$SRC_DIR/scripts/soulacy-launchagent.plist" ]; then
    hdr "Step 4: macOS LaunchAgent (auto-start on login) — optional"
    SETUP_AGENT="n"
    if [ "$INTERACTIVE" -eq 1 ]; then
        read -r -p "  Install LaunchAgent so soulacy starts at login? [y/N]: " SETUP_AGENT
    else
        echo "  Skipping (run install.sh interactively to enable, or set up later)."
    fi
    if [[ "$SETUP_AGENT" =~ ^[Yy]$ ]]; then
        PLIST="$HOME/Library/LaunchAgents/com.soulacy.soulacy.plist"
        mkdir -p "$HOME/Library/LaunchAgents"
        sed -e "s|__SOULACY_BIN__|$BIN_DIR/soulacy|g" -e "s|__HOME__|$HOME|g" \
            "$SRC_DIR/scripts/soulacy-launchagent.plist" > "$PLIST"
        launchctl unload "$PLIST" 2>/dev/null || true
        launchctl load -w "$PLIST"
        ok "LaunchAgent installed — soulacy will start on login"
    fi
fi

# ── Summary ─────────────────────────────────────────────────────────────────
printf "\n${BOLD}  Done.${NC}\n  ────────────────────────────────────────\n"
printf "  Next step:    %s serve\n" "$BIN_DIR/soulacy"
printf "                (or just \`soulacy serve\` once %s is on PATH)\n" "$BIN_DIR"
printf "\n"
printf "  First launch prints a one-time banner with the URL + API key.\n"
printf "  After that, open    http://127.0.0.1:18789\n"
printf "  CLI commands:       sy --help   /   sy doctor   /   sy agent ls\n\n"
