#!/usr/bin/env bash
# Soulacy installer — works two ways:
#
#   One-liner (piped from curl):
#     curl -fsSL https://raw.githubusercontent.com/vmodekurti/soulacy/main/install.sh | bash
#
#   Local checkout:
#     ./install.sh
#
# Defaults are non-interactive and never require sudo:
#   - Binaries land in ~/.local/bin (created if missing).
#   - Runtime config + API key are generated by `soulacy serve` itself
#     on first run (internal/config.EnsureBootstrap) — this script does
#     NOT touch ~/.soulacy/ config so we don't fight the binary's own bootstrap.
#   - One exception: the Studio plugin is copied into the workspace plugins
#     dir (plugin files, not bootstrap state) so it ships by default and
#     hot-reloads from disk.
#
# Environment overrides:
#   SOULACY_PREFIX=/usr/local       install binaries to /usr/local/bin (uses sudo)
#   SOULACY_REF=main                git ref to install (branch / tag / sha)
#   SOULACY_NO_AUTOSTART=1          skip the macOS LaunchAgent step
#   SOULACY_SRC=/path/to/checkout   use an existing checkout instead of cloning

set -euo pipefail

# ── Constants ────────────────────────────────────────────────────────────────
REPO_URL="https://github.com/vmodekurti/soulacy.git"
REF="${SOULACY_REF:-main}"
PREFIX="${SOULACY_PREFIX:-$HOME/.local}"
BIN_DIR="$PREFIX/bin"
NEEDS_SUDO=0
[[ "$BIN_DIR" == /usr/* || "$BIN_DIR" == /opt/* ]] && NEEDS_SUDO=1

# ── Tiny output helpers ──────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'; BOLD='\033[1m'
ok()   { printf "${GREEN}✓${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}⚠${NC}  %s\n" "$*"; }
err()  { printf "${RED}✗${NC} %s\n" "$*" >&2; exit 1; }
hdr()  { printf "\n${BOLD}%s${NC}\n" "$*"; }

printf "\n${BOLD}  Soulacy installer${NC}\n  ────────────────────────────────────────\n\n"

# ── 1. Locate or fetch the source tree ──────────────────────────────────────
hdr "Step 1: Source tree"

# Detect: are we running from inside a soulacy checkout?
SCRIPT_DIR=""
if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

if [ -n "${SOULACY_SRC:-}" ]; then
    SRC_DIR="$SOULACY_SRC"
    ok "Using explicit SOULACY_SRC: $SRC_DIR"
elif [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/go.mod" ] && grep -q soulacy "$SCRIPT_DIR/go.mod"; then
    SRC_DIR="$SCRIPT_DIR"
    ok "Using local checkout: $SRC_DIR"
else
    command -v git >/dev/null 2>&1 || err "git is required to fetch sources. Install git or set SOULACY_SRC=/path/to/checkout."
    SRC_DIR="$(mktemp -d -t soulacy-install.XXXXXX)"
    trap 'rm -rf "$SRC_DIR"' EXIT
    echo "  Cloning $REPO_URL @ $REF → $SRC_DIR"
    git clone --depth 1 --branch "$REF" "$REPO_URL" "$SRC_DIR" 2>&1 | sed 's/^/    /'
    ok "Sources fetched"
fi

# ── 2. Build ────────────────────────────────────────────────────────────────
hdr "Step 2: Build"
command -v go  >/dev/null 2>&1 || err "Go 1.22+ is required. Install from https://go.dev/dl/"
command -v npm >/dev/null 2>&1 || err "npm is required to build the embedded GUI. Install Node.js from https://nodejs.org"
echo "  Go:  $(go version | awk '{print $3}' | sed 's/go//')"
echo "  npm: $(npm --version)"
# `make all` = gui (Svelte build → internal/webui/dist/) + build (Go binaries).
# We need `gui` first because cmd/soulacy embeds dist/ via //go:embed all:dist.
( cd "$SRC_DIR" && make all ) || err "build failed -- see output above"
[ -x "$SRC_DIR/bin/soulacy" ] || err "expected $SRC_DIR/bin/soulacy after build"
[ -x "$SRC_DIR/bin/sy" ]      || err "expected $SRC_DIR/bin/sy after build"
ok "Built bin/soulacy + bin/sy"

# ── 3. Install binaries ─────────────────────────────────────────────────────
hdr "Step 3: Install to $BIN_DIR"
if [ ! -d "$BIN_DIR" ]; then
    if [ "$NEEDS_SUDO" -eq 1 ]; then
        sudo mkdir -p "$BIN_DIR"
    else
        mkdir -p "$BIN_DIR"
    fi
fi

install_one() {
    local src="$1" dst="$2"
    if [ "$NEEDS_SUDO" -eq 1 ]; then
        sudo install -m 0755 "$src" "$dst"
    else
        install -m 0755 "$src" "$dst" 2>/dev/null || { cp "$src" "$dst" && chmod 0755 "$dst"; }
    fi
}

install_one "$SRC_DIR/bin/soulacy" "$BIN_DIR/soulacy"
install_one "$SRC_DIR/bin/sy"      "$BIN_DIR/sy"
ok "Installed: $BIN_DIR/soulacy"
ok "Installed: $BIN_DIR/sy"

# ── 3b. Studio plugin (ships by default) ─────────────────────────────────────
# Studio is a normal plugin: plain files in the workspace plugins dir, loaded
# (and UI hot-reloaded) by the framework. We copy it here so `curl | bash`
# deploys it. `make all` already built its UI into examples/plugins/studio/ui.
hdr "Step 3b: Studio plugin"
WORKSPACE="${SOULACY_WORKSPACE:-$HOME/.soulacy/soulspace}"
PLUGINS_DIR="$WORKSPACE/plugins"
STUDIO_SRC="$SRC_DIR/examples/plugins/studio"
if [ -d "$STUDIO_SRC/ui" ]; then
    rm -rf "$PLUGINS_DIR/studio"
    mkdir -p "$PLUGINS_DIR/studio"
    cp "$STUDIO_SRC/plugin.yaml" "$PLUGINS_DIR/studio/"
    [ -f "$STUDIO_SRC/README.md" ] && cp "$STUDIO_SRC/README.md" "$PLUGINS_DIR/studio/"
    cp -R "$STUDIO_SRC/ui" "$PLUGINS_DIR/studio/ui"
    ok "Studio plugin installed → $PLUGINS_DIR/studio"
else
    warn "Studio UI not built ($STUDIO_SRC/ui missing) — skipping Studio plugin."
fi

# ── 4. PATH check ───────────────────────────────────────────────────────────
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
    warn "$BIN_DIR is NOT on your PATH yet."
    warn "  Add this to your shell rc (~/.zshrc, ~/.bashrc):"
    warn "      export PATH=\"$BIN_DIR:\$PATH\""
    warn "  Then open a new terminal, or run:  export PATH=\"$BIN_DIR:\$PATH\""
fi

# ── 5. Optional: macOS auto-start (only when not piped + on macOS) ──────────
INTERACTIVE=0
[ -t 0 ] && INTERACTIVE=1
if [ "${SOULACY_NO_AUTOSTART:-0}" != "1" ] && [ "$(uname -s)" = "Darwin" ] && [ -f "$SRC_DIR/scripts/soulacy-launchagent.plist" ]; then
    hdr "Step 4: macOS LaunchAgent (auto-start on login) — optional"
    SETUP_AGENT="n"
    if [ "$INTERACTIVE" -eq 1 ]; then
        read -r -p "  Install LaunchAgent so soulacy starts at login? [y/N]: " SETUP_AGENT
    else
        echo "  Skipping (run install.sh interactively to enable, or set up later)."
    fi
    if [[ "$SETUP_AGENT" =~ ^[Yy]$ ]]; then
        PLIST="$HOME/Library/LaunchAgents/com.soulacy.soulacy.plist"
        mkdir -p "$HOME/Library/LaunchAgents"
        sed -e "s|__SOULACY_BIN__|$BIN_DIR/soulacy|g" -e "s|__HOME__|$HOME|g" \
            "$SRC_DIR/scripts/soulacy-launchagent.plist" > "$PLIST"
        launchctl unload "$PLIST" 2>/dev/null || true
        launchctl load -w "$PLIST"
        ok "LaunchAgent installed — soulacy will start on login"
    fi
fi

# ── Summary + guided next steps ─────────────────────────────────────────────
ON_PATH=0
echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR" && ON_PATH=1

printf "\n"
printf "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}\n"
printf "${GREEN}║${NC}  ${BOLD}Soulacy installed.${NC}                                              ${GREEN}║${NC}\n"
printf "${GREEN}║${NC}  soulacy → %-52s ${GREEN}║${NC}\n" "$BIN_DIR/soulacy"
printf "${GREEN}║${NC}  sy      → %-52s ${GREEN}║${NC}\n" "$BIN_DIR/sy"
printf "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}\n\n"

printf "${BOLD}Next steps${NC}\n"
printf "──────────\n"
STEP=1
if [ "$ON_PATH" -eq 0 ]; then
    printf "  ${BOLD}%d.${NC} Add the install dir to PATH for this shell:\n" "$STEP"
    printf "       ${YELLOW}export PATH=\"%s:\$PATH\"${NC}\n" "$BIN_DIR"
    printf "     And for future shells, append the same line to ~/.zshrc or ~/.bashrc.\n\n"
    STEP=$((STEP+1))
fi
printf "  ${BOLD}%d.${NC} Start the gateway. On first run it will:\n" "$STEP"
printf "     • Create ~/.soulacy/soulspace/ with sane defaults\n"
printf "     • Generate an API key (printed once on stderr -- save it)\n"
printf "     • Bind to http://127.0.0.1:18789\n"
printf "     ${YELLOW}soulacy serve${NC}\n\n"
STEP=$((STEP+1))
printf "  ${BOLD}%d.${NC} Open the dashboard, paste the key from the banner:\n" "$STEP"
printf "     ${YELLOW}http://127.0.0.1:18789${NC}\n\n"
STEP=$((STEP+1))
printf "  ${BOLD}%d.${NC} Try the CLI:\n" "$STEP"
printf "     ${YELLOW}sy doctor${NC}            -- check the workspace\n"
printf "     ${YELLOW}sy agent ls${NC}          -- list installed agents\n"
printf "     ${YELLOW}sy --help${NC}            -- everything else\n\n"

# Offer to launch right now (only when stdin is a tty -- piped curl|bash skips).
if [ -t 0 ]; then
    printf "──────────\n"
    read -r -p "Launch the gateway now? [Y/n]: " LAUNCH
    LAUNCH="${LAUNCH:-Y}"
    if [[ "$LAUNCH" =~ ^[Yy]$ ]]; then
        printf "\nStarting ${BOLD}soulacy serve${NC} ... (Ctrl-C to stop)\n\n"
        export PATH="$BIN_DIR:$PATH"
        exec "$BIN_DIR/soulacy" serve
    fi
else
    printf "Run ${BOLD}soulacy serve${NC} now to start. The banner with your API key prints on first launch.\n\n"
fi
