#!/usr/bin/env bash
# Soulacy installer — works two ways:
#
#   One-liner (piped from curl):
#     curl -fsSL https://raw.githubusercontent.com/vmodekurti/soulacy/main/install.sh | bash
#
#   Local checkout:
#     ./install.sh
#
# Install strategy (one story):
#   1. Try to download this platform's prebuilt release tarball from
#      GitHub releases (soulacy_<version>_<os>_<arch>.tar.gz, produced by
#      .github/workflows/release.yml). Fast path, no toolchain needed.
#   2. If no matching release asset exists (e.g. installing from a branch,
#      or before the first tagged release), fall back to building from
#      source via `make all`.
#
# Defaults are non-interactive and never require sudo:
#   - Binaries land in ~/.local/bin (created if missing).
#   - Runtime config + API key are generated by `soulacy serve` itself
#     on first run (internal/config.EnsureBootstrap) — this script does
#     NOT touch ~/.soulacy/ config so we don't fight the binary's own bootstrap.
#   - One exception: the Studio plugin is copied into the workspace plugins
#     dir (plugin files, not bootstrap state) so it ships by default and
#     hot-reloads from disk.
#
# Environment overrides:
#   SOULACY_PREFIX=/usr/local       install binaries to /usr/local/bin (uses sudo)
#   SOULACY_REF=main                git ref / release tag to install (branch / tag / sha)
#   SOULACY_VERSION=v1.2.3          release tag to download (defaults to SOULACY_REF, else latest)
#   SOULACY_FROM_SOURCE=1           skip the tarball download and always build from source
#   SOULACY_NO_AUTOSTART=1          skip the macOS LaunchAgent step
#   SOULACY_SRC=/path/to/checkout   use an existing checkout instead of cloning

set -euo pipefail

# ── Constants ────────────────────────────────────────────────────────────────
REPO="vmodekurti/soulacy"
REPO_URL="https://github.com/${REPO}.git"
REF="${SOULACY_REF:-main}"
PREFIX="${SOULACY_PREFIX:-$HOME/.local}"
BIN_DIR="$PREFIX/bin"
NEEDS_SUDO=0
[[ "$BIN_DIR" == /usr/* || "$BIN_DIR" == /opt/* ]] && NEEDS_SUDO=1

TOOLCHAIN="${HOME}/.soulacy/toolchain"
GO_VERSION="1.25.11"
NODE_VERSION="22.12.0"

# Detect an existing config up-front (BEFORE anything is written) so we only run
# the first-time setup wizard on a genuinely fresh install.
CONFIG_LEGACY="$HOME/.soulacy/config.yaml"
CONFIG_WORKSPACE="$HOME/.soulacy/soulspace/config.yaml"
CONFIG_EXISTS=0
if [ -f "$CONFIG_LEGACY" ] || [ -f "$CONFIG_WORKSPACE" ]; then CONFIG_EXISTS=1; fi

# ── Tiny output helpers ──────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'; BOLD='\033[1m'
ok()   { printf "${GREEN}✓${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}⚠${NC}  %s\n" "$*"; }
err()  { printf "${RED}✗${NC} %s\n" "$*" >&2; exit 1; }
hdr()  { printf "\n${BOLD}%s${NC}\n" "$*"; }

ensure_go() {
    if command -v go >/dev/null 2>&1; then
        local local_ver
        local_ver="$(go version | awk '{print $3}' | sed 's/go//')"
        local major minor
        major=$(echo "$local_ver" | cut -d. -f1)
        minor=$(echo "$local_ver" | cut -d. -f2)
        if [ "$major" -gt 1 ] || { [ "$major" -eq 1 ] && [ "$minor" -ge 25 ]; }; then
            return 0
        fi
        warn "Local Go version ($local_ver) is lower than the required 1.25+."
    fi
    if [ -x "${TOOLCHAIN}/go/bin/go" ]; then
        export PATH="${TOOLCHAIN}/go/bin:${PATH}"
        return 0
    fi

    local install_go="n"
    if [ -t 0 ]; then
        read -r -p "  Go 1.25+ is required. Install Go ${GO_VERSION} privately to ${TOOLCHAIN}? [Y/n]: " install_go
        install_go="${install_go:-Y}"
    elif [ -c /dev/tty ] && { read -r -p "  Go 1.25+ is required. Install Go ${GO_VERSION} privately to ${TOOLCHAIN}? [Y/n]: " install_go < /dev/tty; } 2>/dev/null; then
        install_go="${install_go:-Y}"
    else
        install_go="Y"
    fi

    if [[ "$install_go" =~ ^[Yy]$ ]]; then
        echo "  Installing Go ${GO_VERSION} privately to ${TOOLCHAIN} (no system changes)..."
        mkdir -p "$TOOLCHAIN"
        local os arch
        os="$(uname -s | tr '[:upper:]' '[:lower:]')"
        arch="$(uname -m)"
        case "$arch" in
            x86_64)        arch="amd64" ;;
            aarch64|arm64) arch="arm64" ;;
        esac
        curl -fsSL "https://go.dev/dl/go${GO_VERSION}.${os}-${arch}.tar.gz" | tar -xz -C "$TOOLCHAIN"
        export PATH="${TOOLCHAIN}/go/bin:${PATH}"
        ok "Go $(go version | awk '{print $3}') ready"
    else
        err "Go 1.25+ is required. Install from https://go.dev/dl/"
    fi
}

ensure_node() {
    if command -v npm >/dev/null 2>&1; then return 0; fi
    local arch os node_arch node_dir
    arch="$(uname -m)"
    os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    node_arch="$arch"
    [ "$node_arch" = "x86_64" ] && node_arch="x64"
    [ "$node_arch" = "amd64" ] && node_arch="x64"
    node_dir="${TOOLCHAIN}/node-v${NODE_VERSION}-${os}-${node_arch}"
    if [ -x "${node_dir}/bin/npm" ]; then
        export PATH="${node_dir}/bin:${PATH}"
        return 0
    fi

    local install_node="n"
    if [ -t 0 ]; then
        read -r -p "  npm is required but not found. Install Node ${NODE_VERSION} privately to ${TOOLCHAIN}? [Y/n]: " install_node
        install_node="${install_node:-Y}"
    elif [ -c /dev/tty ] && { read -r -p "  npm is required but not found. Install Node ${NODE_VERSION} privately to ${TOOLCHAIN}? [Y/n]: " install_node < /dev/tty; } 2>/dev/null; then
        install_node="${install_node:-Y}"
    else
        install_node="Y"
    fi

    if [[ "$install_node" =~ ^[Yy]$ ]]; then
        echo "  Installing Node ${NODE_VERSION} privately to ${TOOLCHAIN} (no system changes)..."
        mkdir -p "$TOOLCHAIN"
        curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-${os}-${node_arch}.tar.gz" | tar -xz -C "$TOOLCHAIN"
        export PATH="${node_dir}/bin:${PATH}"
        ok "Node $(node --version) ready"
    else
        err "npm is required to build the embedded GUI. Install Node.js from https://nodejs.org"
    fi
}

printf "\n${BOLD}  Soulacy installer${NC}\n  ────────────────────────────────────────\n\n"

# ── 0. Fast path: download a prebuilt release tarball ────────────────────────
# Release assets are named soulacy_<version>_<os>_<arch>.tar.gz and each
# tarball contains both the `soulacy` and `sy` binaries. If we can grab one,
# we skip the whole source build (no Go/npm needed). Falls back silently to
# the build-from-source path below on any failure.
DOWNLOADED=0
DL_DIR=""

detect_os_arch() {
    DL_OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
    DL_ARCH="$(uname -m)"
    case "$DL_ARCH" in
        x86_64)        DL_ARCH="amd64" ;;
        aarch64|arm64) DL_ARCH="arm64" ;;
        *) return 1 ;;
    esac
    case "$DL_OS" in linux|darwin) ;; *) return 1 ;; esac
    return 0
}

try_download_release() {
    [ "${SOULACY_FROM_SOURCE:-0}" = "1" ] && return 1
    command -v curl >/dev/null 2>&1 || return 1
    command -v tar  >/dev/null 2>&1 || return 1
    detect_os_arch || return 1

    # Resolve the version to download: explicit > ref (if it looks like a tag) > latest.
    local version="${SOULACY_VERSION:-}"
    if [ -z "$version" ]; then
        case "$REF" in
            v[0-9]*) version="$REF" ;;          # SOULACY_REF is a release tag
            main|"") version="latest" ;;        # default branch → latest release
            *)       return 1 ;;                 # arbitrary branch/sha → build from source
        esac
    fi
    if [ "$version" = "latest" ]; then
        version="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" 2>/dev/null \
            | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/' || true)"
        [ -n "$version" ] || return 1
    fi

    local tarball="soulacy_${version}_${DL_OS}_${DL_ARCH}.tar.gz"
    local url="https://github.com/${REPO}/releases/download/${version}/${tarball}"
    DL_DIR="$(mktemp -d -t soulacy-dl.XXXXXX)"
    echo "  Trying release asset: $tarball"
    if curl -fsSL -o "${DL_DIR}/${tarball}" "$url" 2>/dev/null \
        && tar -xzf "${DL_DIR}/${tarball}" -C "$DL_DIR" 2>/dev/null \
        && [ -f "${DL_DIR}/soulacy" ] && [ -f "${DL_DIR}/sy" ]; then
        chmod +x "${DL_DIR}/soulacy" "${DL_DIR}/sy"
        DOWNLOADED=1
        DOWNLOADED_VERSION="$version"
        return 0
    fi
    rm -rf "$DL_DIR"; DL_DIR=""
    return 1
}

hdr "Step 1: Acquire binaries"
if try_download_release; then
    ok "Downloaded prebuilt release ${DOWNLOADED_VERSION} for ${DL_OS}/${DL_ARCH}"
    BUILT_SOULACY="${DL_DIR}/soulacy"
    BUILT_SY="${DL_DIR}/sy"
    SRC_DIR=""   # no source tree when using a prebuilt tarball
    trap 'rm -rf "$DL_DIR"' EXIT
else
    warn "No matching release asset — building from source."
fi

# ── 1. Locate or fetch the source tree (only when not downloaded) ────────────
if [ "$DOWNLOADED" -eq 0 ]; then
hdr "Step 1b: Source tree"

# Detect: are we running from inside a soulacy checkout?
SCRIPT_DIR=""
if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

if [ -n "${SOULACY_SRC:-}" ]; then
    SRC_DIR="$SOULACY_SRC"
    ok "Using explicit SOULACY_SRC: $SRC_DIR"
elif [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/go.mod" ] && grep -q soulacy "$SCRIPT_DIR/go.mod"; then
    SRC_DIR="$SCRIPT_DIR"
    ok "Using local checkout: $SRC_DIR"
else
    command -v git >/dev/null 2>&1 || err "git is required to fetch sources. Install git or set SOULACY_SRC=/path/to/checkout."
    SRC_DIR="$(mktemp -d -t soulacy-install.XXXXXX)"
    trap 'rm -rf "$SRC_DIR"' EXIT
    echo "  Cloning $REPO_URL @ $REF → $SRC_DIR"
    git clone --depth 1 --branch "$REF" "$REPO_URL" "$SRC_DIR" 2>&1 | sed 's/^/    /'
    ok "Sources fetched"
fi

# ── 2. Build ────────────────────────────────────────────────────────────────
hdr "Step 2: Build"
ensure_go
ensure_node
echo "  Go:  $(go version | awk '{print $3}' | sed 's/go//')"
echo "  npm: $(npm --version)"
# `make all` = gui (Svelte build → internal/webui/dist/) + build (Go binaries).
# We need `gui` first because cmd/soulacy embeds dist/ via //go:embed all:dist.
( cd "$SRC_DIR" && make all ) || err "build failed -- see output above"
[ -x "$SRC_DIR/bin/soulacy" ] || err "expected $SRC_DIR/bin/soulacy after build"
[ -x "$SRC_DIR/bin/sy" ]      || err "expected $SRC_DIR/bin/sy after build"
ok "Built bin/soulacy + bin/sy"
BUILT_SOULACY="$SRC_DIR/bin/soulacy"
BUILT_SY="$SRC_DIR/bin/sy"

fi   # end: build-from-source path (DOWNLOADED -eq 0)

# ── 3. Install binaries ─────────────────────────────────────────────────────
hdr "Step 3: Install to $BIN_DIR"
if [ ! -d "$BIN_DIR" ]; then
    if [ "$NEEDS_SUDO" -eq 1 ]; then
        sudo mkdir -p "$BIN_DIR"
    else
        mkdir -p "$BIN_DIR"
    fi
fi

install_one() {
    local src="$1" dst="$2"
    if [ "$NEEDS_SUDO" -eq 1 ]; then
        sudo install -m 0755 "$src" "$dst"
    else
        install -m 0755 "$src" "$dst" 2>/dev/null || { cp "$src" "$dst" && chmod 0755 "$dst"; }
    fi
}

install_one "$BUILT_SOULACY" "$BIN_DIR/soulacy"
install_one "$BUILT_SY"      "$BIN_DIR/sy"
ok "Installed: $BIN_DIR/soulacy"
ok "Installed: $BIN_DIR/sy"

# ── 3b. Studio (built into the dashboard) ────────────────────────────────────
# ARCH-6: Studio is no longer a separate plugin copied into the workspace. The
# visual builder is compiled directly into the core GUI (`make gui` →
# internal/webui/dist, embedded in the gateway binary), so it works out of the
# box with zero extra install steps and no <workspace>/plugins/studio directory.

# ── 4. PATH setup — make the CLI work out of the box ─────────────────────────
# A child process can't mutate the parent shell's PATH, so for the *current*
# terminal the user still has to start a new shell (or source their rc). What we
# CAN do is (a) make soulacy/sy available for the rest of THIS install run (so
# the setup wizard below works), and (b) idempotently append the PATH line to
# the right shell rc file(s) so every NEW terminal has the CLI automatically —
# no manual editing required.
PATH_MARKER="# added by soulacy installer"
PATH_RC_UPDATED=0  # set to 1 when we append the PATH line to a shell rc

append_path_to_rc() {
    # $1 = rc file path.
    #   return 0 → line newly appended
    #   return 2 → already present (idempotent no-op)
    #   return 1 → could not write
    local rc="$1"
    [ -e "$rc" ] || { touch "$rc" 2>/dev/null || return 1; }
    # Idempotent: don't double-add on re-install/upgrade.
    if grep -qF "$PATH_MARKER" "$rc" 2>/dev/null || grep -qsF "$BIN_DIR" "$rc" 2>/dev/null; then
        return 2
    fi
    printf '\n# Soulacy CLI (soulacy, sy) %s\nexport PATH="%s:$PATH"\n' \
        "$PATH_MARKER" "$BIN_DIR" >> "$rc" || return 1
    return 0
}

if echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
    : # already on PATH (e.g. SOULACY_PREFIX=/usr/local) — nothing to do
else
    # Decide which rc files to write. Cover the user's login shell, and on macOS
    # also zsh (the OS default) so a future bash→zsh switch still works.
    case "$(basename "${SHELL:-sh}")" in
        zsh)  RC_TARGETS="$HOME/.zshrc" ;;
        bash) RC_TARGETS="$HOME/.bash_profile $HOME/.bashrc" ;;
        *)    RC_TARGETS="$HOME/.profile" ;;
    esac
    if [ "$(uname -s)" = "Darwin" ]; then
        case " $RC_TARGETS " in *" $HOME/.zshrc "*) ;; *) RC_TARGETS="$RC_TARGETS $HOME/.zshrc" ;; esac
    fi

    ADDED_RCS=""    # files we appended to this run
    PRESENT_RCS=""  # files that already had it (re-install/upgrade)
    for rc in $RC_TARGETS; do
        append_path_to_rc "$rc"; rc_rc=$?
        case "$rc_rc" in
            0) ADDED_RCS="$ADDED_RCS ${rc/#$HOME/~}" ;;
            2) PRESENT_RCS="$PRESENT_RCS ${rc/#$HOME/~}" ;;
        esac
    done

    # Make the CLI usable for the remainder of this install run.
    export PATH="$BIN_DIR:$PATH"

    if [ -n "$ADDED_RCS" ]; then
        PATH_RC_UPDATED=1
        ok "Added $BIN_DIR to PATH in:$ADDED_RCS"
        warn "Already-open terminals won't see it until you open a new one (or 'source' the rc above)."
    elif [ -n "$PRESENT_RCS" ]; then
        # Upgrade case: rc already wired, but the running shell that launched the
        # installer may still be stale — flag it so Next Steps reminds them.
        PATH_RC_UPDATED=1
        ok "PATH already configured in:$PRESENT_RCS"
    else
        warn "$BIN_DIR is not on PATH and I couldn't update your shell rc automatically."
        warn "  Add this line manually:  export PATH=\"$BIN_DIR:\$PATH\""
    fi
fi

# ── 5. Optional: macOS auto-start (only when not piped + on macOS) ──────────
INTERACTIVE=0
[ -t 0 ] && INTERACTIVE=1
if [ "${SOULACY_NO_AUTOSTART:-0}" != "1" ] && [ "$(uname -s)" = "Darwin" ] && [ -f "$SRC_DIR/scripts/soulacy-launchagent.plist" ]; then
    hdr "Step 4: macOS LaunchAgent (auto-start on login) — optional"
    SETUP_AGENT="n"
    if [ "$INTERACTIVE" -eq 1 ]; then
        read -r -p "  Install LaunchAgent so soulacy starts at login? [y/N]: " SETUP_AGENT
    else
        echo "  Skipping (run install.sh interactively to enable, or set up later)."
    fi
    if [[ "$SETUP_AGENT" =~ ^[Yy]$ ]]; then
        PLIST="$HOME/Library/LaunchAgents/com.soulacy.soulacy.plist"
        mkdir -p "$HOME/Library/LaunchAgents"
        sed -e "s|__SOULACY_BIN__|$BIN_DIR/soulacy|g" -e "s|__HOME__|$HOME|g" \
            "$SRC_DIR/scripts/soulacy-launchagent.plist" > "$PLIST"
        launchctl unload "$PLIST" 2>/dev/null || true
        launchctl load -w "$PLIST"
        ok "LaunchAgent installed — soulacy will start on login"
    fi
fi

# ── Summary + guided next steps ─────────────────────────────────────────────
ON_PATH=0
echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR" && ON_PATH=1

printf "\n"
printf "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}\n"
printf "${GREEN}║${NC}  ${BOLD}Soulacy installed.${NC}                                              ${GREEN}║${NC}\n"
printf "${GREEN}║${NC}  soulacy → %-52s ${GREEN}║${NC}\n" "$BIN_DIR/soulacy"
printf "${GREEN}║${NC}  sy      → %-52s ${GREEN}║${NC}\n" "$BIN_DIR/sy"
printf "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}\n\n"

# ── First-time setup wizard (fresh install, terminal available) ──────────────
# Guides the user through provider/model + web search + an API key, writing the
# config so the gateway is ready on first launch. Runs whenever a terminal is
# reachable — including `curl | bash`, where stdin is the pipe but the wizard
# reads from /dev/tty. Skipped for upgrades (config already present) and truly
# non-interactive shells (no tty, e.g. CI).
if [ "$CONFIG_EXISTS" -eq 0 ] && { [ -t 0 ] || [ -c /dev/tty ]; }; then
    hdr "First-time setup"
    printf "  No existing config found — let's get you configured.\n\n"
    export PATH="$BIN_DIR:$PATH"
    SETUP_RC=0
    if [ -t 0 ]; then
        "$BIN_DIR/sy" onboard || SETUP_RC=$?
    else
        # stdin is a pipe (curl | bash) — feed the wizard from the terminal.
        "$BIN_DIR/sy" onboard < /dev/tty || SETUP_RC=$?
    fi
    if [ "$SETUP_RC" -eq 0 ]; then
        # Re-detect: setup just wrote the config.
        { [ -f "$CONFIG_LEGACY" ] || [ -f "$CONFIG_WORKSPACE" ]; } && CONFIG_EXISTS=1
    else
        warn "Setup did not complete — re-run it any time with:  sy onboard"
    fi
fi

printf "${BOLD}Next steps${NC}\n"
printf "──────────\n"
STEP=1
if [ "$PATH_RC_UPDATED" -eq 1 ]; then
    # We already wired PATH into the shell rc — the only thing left is to use a
    # shell that has loaded it.
    printf "  ${BOLD}%d.${NC} Open a ${BOLD}new terminal${NC} (your PATH was set up automatically),\n" "$STEP"
    printf "     or run this once in THIS terminal:\n"
    printf "       ${YELLOW}export PATH=\"%s:\$PATH\"${NC}\n\n" "$BIN_DIR"
    STEP=$((STEP+1))
elif [ "$ON_PATH" -eq 0 ]; then
    printf "  ${BOLD}%d.${NC} Add the install dir to PATH for this shell:\n" "$STEP"
    printf "       ${YELLOW}export PATH=\"%s:\$PATH\"${NC}\n" "$BIN_DIR"
    printf "     And for future shells, append the same line to ~/.zshrc or ~/.bashrc.\n\n"
    STEP=$((STEP+1))
fi
printf "  ${BOLD}%d.${NC} Start the gateway. On first run it will:\n" "$STEP"
printf "     • Create ~/.soulacy/soulspace/ with sane defaults\n"
printf "     • Generate an API key (printed once on stderr -- save it)\n"
printf "     • Bind to http://127.0.0.1:18789\n"
printf "     ${YELLOW}soulacy serve${NC}\n\n"
STEP=$((STEP+1))
printf "  ${BOLD}%d.${NC} Open the dashboard, paste the key from the banner:\n" "$STEP"
printf "     ${YELLOW}http://127.0.0.1:18789${NC}\n\n"
STEP=$((STEP+1))
printf "  ${BOLD}%d.${NC} Try the CLI:\n" "$STEP"
printf "     ${YELLOW}sy doctor${NC}            -- check the workspace\n"
printf "     ${YELLOW}sy agent ls${NC}          -- list installed agents\n"
printf "     ${YELLOW}sy --help${NC}            -- everything else\n\n"

# ── KEY THINGS TO REMEMBER: show the configured API key prominently ──────────
# Read server.api_key from whichever config exists (the FIRST api_key: line is
# the server key, written near the top of the file). Shown for both fresh and
# upgrade installs so the user always knows their dashboard key.
CONFIG_FILE=""
[ -f "$CONFIG_WORKSPACE" ] && CONFIG_FILE="$CONFIG_WORKSPACE"
[ -z "$CONFIG_FILE" ] && [ -f "$CONFIG_LEGACY" ] && CONFIG_FILE="$CONFIG_LEGACY"
API_KEY=""
if [ -n "$CONFIG_FILE" ]; then
    API_KEY=$(grep -E '^[[:space:]]*api_key:[[:space:]]*"' "$CONFIG_FILE" | head -1 | sed -E 's/^[^"]*"([^"]*)".*/\1/')
fi
if [ -n "$API_KEY" ]; then
    printf "${YELLOW}${BOLD}━━━━━━━━━━━━━━━━━━━━━━  KEY THINGS TO REMEMBER  ━━━━━━━━━━━━━━━━━━━━━━${NC}\n\n"
    printf "  ${BOLD}Your Soulacy API key${NC} ${YELLOW}(paste this to log into the dashboard)${NC}:\n\n"
    printf "      ${GREEN}${BOLD}%s${NC}\n\n" "$API_KEY"
    printf "  Save it now — it gates the dashboard and every API call. It lives in:\n"
    printf "      ${YELLOW}%s${NC}\n" "$CONFIG_FILE"
    printf "${YELLOW}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n\n"
fi

# Offer to launch right now whenever a terminal is reachable (incl. curl | bash,
# reading the answer from /dev/tty). Truly non-interactive shells just get the
# hint.
if [ -t 0 ] || [ -c /dev/tty ]; then
    printf "──────────\n"
    LAUNCH="Y"
    if [ -t 0 ]; then
        read -r -p "Launch the gateway now? [Y/n]: " LAUNCH || true
    else
        read -r -p "Launch the gateway now? [Y/n]: " LAUNCH < /dev/tty || true
    fi
    LAUNCH="${LAUNCH:-Y}"
    if [[ "$LAUNCH" =~ ^[Yy]$ ]]; then
        printf "\nStarting ${BOLD}soulacy serve${NC} ... (Ctrl-C to stop)\n\n"
        export PATH="$BIN_DIR:$PATH"
        exec "$BIN_DIR/soulacy" serve
    fi
else
    printf "Run ${BOLD}soulacy serve${NC} now to start. The banner with your API key prints on first launch.\n\n"
fi
